Remove design doc for PR review aid.
DMSC-Instrument-Data/MDSpaceFillingPrototype pull request #26
Opened 2018-11-13 10:32 UTC by SimonHeybrock

2018-11-13 20:56 UTC, OwenArnold requested changes
Great start. Thanks Igor.

2018-11-13 20:56 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> -MDEvent object as small as possible. To reach this the floating point coordinates can be thrown out the MDEvent structure
Can we also adopt a mdleanevent and drop the run and detector id information? Does that provide any worthwhile improvement?

2018-11-13 20:56 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> -3. Fixed global box, the initial box can't grow with adding next portion of events, the boundaries should be defined
Good point, but maybe reword slightly to say "Fixed global boundaries are necessary. Unlike the current MDEventWorkspace, the boxes will not dynamically grow when mdevents are added. The user will need to determine the static size before events are added." you could go on to say: "This is because morton numbers are determined by the extents in the world coordinates of the space".

2018-11-13 20:56 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> -
I would go further and briefly mention the various options that have been considered in separate headings. The wider dev community will probably ask about this, Briefly explaining why those routes are not advantageous would be a good idea.

2018-11-15 09:38 UTC, DanNixon commented on docs/MDSpaceDesign.md
> -1. Loosing the split factor (SplitInfo) as a parameter: automatically fixed as 2 for every axes of the box.
Yes, the factor just needs to be a power of 2 and constant for all axes.

(I hadn't considered the effects of setting this so left it hard coded at 2)

2018-11-21 15:24 UTC, igudich commented
I would create anew one in the proper branch.

2018-11-21 15:24 UTC, closed without merging