Design doc
DMSC-Instrument-Data/MDSpaceFillingPrototype pull request #27
Opened 2018-11-21 15:26 UTC by igudich

Request to discuss the design documentation related to MD workspace structure.

2018-11-22 06:46 UTC, SimonHeybrock requested changes
Good update and very nice drawings that help to illustrate the mechanism. See some comments below.

2018-11-22 06:46 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +reimplementation in current version.
See my question on Slack: How do you ensure that Morton numbers and coordinates are in sync, without changing the current interface (i.e., there is no `setCoord` where you could update the Morton number)?

2018-11-22 06:46 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +so bounding box could be passed as an argument to this switch function.
I am not yet convinced that this would be less effort than option 3., and it feels more risky in terms of bugs that may occur in the future.

2018-11-22 06:46 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +transform only the top level bounding box. This option is the most labor-consuming.
1 month? 1 year? 10 years?

2018-11-22 06:46 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +The proposed implementation will not affect any external storage formats.
.... because you convert back to floating point coordinates?

2018-11-22 06:46 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> + the same for each dimension.
I think it is the same for each dimension also now.

2018-11-22 06:46 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +once from instrument or sample geometry.
Maybe add a note here that it *can* actually be changed, but is as costly as building the whole MD workspace from scratch. And even then there is precision loss.

Furthermore, I would also discuss that for sufficiently large integers (such as 128 bit) we can simply make the default box "very large", without losing a significant amount of precision. That is, for all practical purposes it could be considered unbounded.

Finally, you should also mention here what you intend to do if you encounter an event outside the global box. I suppose it would be discarded (note some additional overhead from checking for out-of-bounds events).

2018-11-22 06:46 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +and twice more for 128bit Morton number. Of course it always better to have more precision than less, but the length of
I would give the bin count (per dimension) here. The depth itself is not such a useful number.

Furthermore, I would note that:
- We think that 128 bit should be enough for all possible scenarios.
- 64 bit maybe be sufficient for many scenarios.
- The implementation could probably be such that it is possible to select between 64 bit and 128 bit?
- More than 4 dimensions can also be supported, by either having fewer bits per dimensions, or using even longer integers.

2018-11-22 06:48 UTC, SimonHeybrock commented
I forgot to mention: You should also have a look at the Python exports of the MD data structures and see if the interface changes required for option 3.) break any Python API.

2018-11-22 09:22 UTC, OwenArnold requested changes
Thanks for including the options @igudich it's very helpful to weigh up the available options. 

I've made a few comments to be addressed.

2018-11-22 09:22 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +#####2. Keep only coordinates.
@igudich we talked about measuring this. i.e just performing the sort with the morton numbers computed on the fly. Do you have results for this, if so could you add here please?

2018-11-22 09:22 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +We can lose accuracy comparing with floating point coordinates in some cases, but can choose longer Morton number to be
I believe that there are benchmarks for the conversion for this. I think Dan put some together. Can you summarise results here.

2018-11-22 09:22 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +And also we need to reimplement all functions that change the floating point coordinates (workspace tranformations) to
I'm not sure what you mean when you say: *And also we need to reimplement all functions that change the floating point coordinates (workspace tranformations) to       
transform only the top level bounding box*?

2018-11-22 09:22 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +Morton number in 3d space), we also need to control the state of this single piece of memory. The switching operation
Ok, so this is why you mentioned unions in one of our earlier discussions

2018-11-22 09:22 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +so bounding box could be passed as an argument to this switch function.
At which key points in the workflow are you recommending switching between floats and unsigned integer?

2018-11-22 09:22 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +once from instrument or sample geometry.
Interesting points. Changing the box boundaries would definitely result in having to change the morton numbers. But would the sort order necessarily change of our morton numbers, or could our vectors be transformed in-place?

2018-11-22 09:55 UTC, igudich commented on docs/MDSpaceDesign.md
> + the same for each dimension.
The API provide the possibility to provide separate factor for each axis, http://docs.mantidproject.org/nightly/algorithms/ConvertToMD-v1.html, SplitInfo parameter: A comma separated list of into how many sub-grid elements each dimension should split; or just one to split into the same number for all dimensions. Default 5.

2018-11-22 10:01 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> + the same for each dimension.
Good point Igor. Though, based on my knowledge of the workflows, I'd be very surprised if this was really being used.

2018-11-22 10:02 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> + the same for each dimension.
As in, I would be surprised if different splitting intos were really being used for different dimensions.

2018-11-22 10:03 UTC, igudich commented on docs/MDSpaceDesign.md
> +once from instrument or sample geometry.
@OwenArnold, the Morton number as well as the sorting order
![img-0168](https://user-images.githubusercontent.com/21035795/48895801-3d65c000-ee46-11e8-8701-3f454dcc1d20.JPG)

2018-11-22 10:19 UTC, igudich commented on docs/MDSpaceDesign.md
> +reimplementation in current version.
My answer on Slack)
Igor Gudich [8:55 AM]
Morton number only reflects the relation to the initial top level box. So, there is no need to synchronize with coordinates in the case of transformations. And forbid expanding global box during appending events.Ву the way I have not seen this in the addEvent(s) functions.

2018-11-22 10:20 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +reimplementation in current version.
... but you still need to disable direct write access to the coordinates.

2018-11-22 10:23 UTC, igudich commented on docs/MDSpaceDesign.md
> +so bounding box could be passed as an argument to this switch function.
In principal we can hide switching on the low level: each API function knows what kind of data it requires coordinates or Morton number and can switch itself. The key point is of course constructing (merging, appending events). We may allow to switch the state for constructing and appending events only, after this operation the state would be restored to the fp coordinates internally:
```c++
void MDWorkspace::appendEvents( EventsType events) {
   switch_to_morton_numbers();
// append events here
   switch_to_coordinates();
}
```
Something like this. All other functionality stays the same completely.

2018-11-22 10:49 UTC, igudich commented on docs/MDSpaceDesign.md
> +transform only the top level bounding box. This option is the most labor-consuming.
Several months: 3-4 of coding and testing to be optimistic, also depends on the amount of refactoring we want to do on this. Should I elaborate this in the document?

2018-11-22 11:08 UTC, igudich commented on docs/MDSpaceDesign.md
> +We can lose accuracy comparing with floating point coordinates in some cases, but can choose longer Morton number to be
I haven't seen any tests related to accuracy. Do you mean the benchmarking of retrieving the coordinates from Morton numbers of different length? I would add the links to the all Dans documentation if we would have correct benchmarking results where.

2018-11-22 11:37 UTC, igudich commented on docs/MDSpaceDesign.md
> +And also we need to reimplement all functions that change the floating point coordinates (workspace tranformations) to
Current implementation has a functionality related to the space transformations (shifting, scaling), this transformations require changing the coordinates, but not the Morton numbers. I case of storing Morton numbers we need to address this transformations to the top level bounding box only.

2018-11-22 11:47 UTC, igudich commented on docs/MDSpaceDesign.md
> +#####2. Keep only coordinates.
I have not measured this because it should be much worse, but I could do I think, it is not very complicated.

2018-11-22 11:53 UTC, igudich commented on docs/MDSpaceDesign.md
> +reimplementation in current version.
The Idea is that the Mortom number would't be changed after the creating the event.

2018-11-22 12:38 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +transform only the top level bounding box. This option is the most labor-consuming.
Yes, of course.

2018-11-22 14:23 UTC, igudich commented on docs/MDSpaceDesign.md
> +#####2. Keep only coordinates.
Well, here are results for 10000000 millions of events:
------------------------------------------------------------------------------
Benchmark                                       Time           CPU Iterations
------------------------------------------------------------------------------
BM_sorting_morton<uint8_t, uint32_t>           13 ms         12 ms         65
BM_sorting_morton<uint16_t, uint64_t>          17 ms         14 ms         48
BM_sorting_morton<uint32_t, uint128_t>         38 ms         28 ms         27
BM_sorting_morton<uint64_t, uint256_t>        108 ms         55 ms         10
BM_sorting_coords<uint8_t, uint32_t>          372 ms        268 ms         10
BM_sorting_coords<uint16_t, uint64_t>         476 ms        367 ms         10
BM_sorting_coords<uint32_t, uint128_t>        744 ms        571 ms         10
BM_sorting_coords<uint64_t, uint256_t>      34008 ms          1 ms          1

On the flight sorting is 10 times slower, as you can see.

2018-11-22 14:45 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +We can lose accuracy comparing with floating point coordinates in some cases, but can choose longer Morton number to be
Yes, I did mean the benchmarking of the deinterleave and float(s) creation.

2018-11-22 14:58 UTC, igudich commented on docs/MDSpaceDesign.md
> +We can lose accuracy comparing with floating point coordinates in some cases, but can choose longer Morton number to be
There are some benchmarks, but what should I compare with?

2018-11-22 15:50 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +We can lose accuracy comparing with floating point coordinates in some cases, but can choose longer Morton number to be
I think @DanNixon would be better to comment on this, but his approach was to try to establish what the cost of that conversion was in relation to the cost of the sort. I think we also discussed that the splatter plot in the 3D vates-simple-interface is the only place that raw access to floats for our md events is actually required. Float access is also used in things like multi-dimensional rebinning, but theoretically that part can be changed to using morton numbers.

2018-11-22 16:02 UTC, igudich commented on docs/MDSpaceDesign.md
> +We can lose accuracy comparing with floating point coordinates in some cases, but can choose longer Morton number to be
I've measured this relation while had been working on this approach: the retrieving coordinates and reverse procedure are less than 10% of sorting. I will do some more measurements.

2018-11-22 16:05 UTC, DanNixon commented on docs/MDSpaceDesign.md
> +We can lose accuracy comparing with floating point coordinates in some cases, but can choose longer Morton number to be
Half the problem is that there is nothing to compare it with. The equivalent operation in Mantid is a lookup so you are only bound by whatever memory the value needs to be fetched from.

Ideally those benchmarks should be used to determine if the attainable event rate is sufficient for whatever visualisation you want to perform (this isn't an area I'm overly familiar with so was not something I got round to doing).

A general rule I applied was that this even rate was of lower priority as it was only sampling the events, not operating over all of them.

Also, I did put in a prototype that used the deinterleaved integers for an MD rebin, that required a simple change to the transformation to bin index. I didn't find a way to do this with Morton numbers that was faster than deinterleaving and a matrix multiplication.

2018-11-23 08:42 UTC, OwenArnold commented on docs/MDSpaceDesign.md
> +We can lose accuracy comparing with floating point coordinates in some cases, but can choose longer Morton number to be
Yes, only one aspect of visualisation needs the fully resolved mdevent coordinates, As far as the "splatter plot view" in the VSI goes, that is very niche visualisation that's not frequently used. Furthermore it takes a sampling approach to get the MDEvents in the first place so is only requesting coordinates from a small fraction (by default) of the total. As a result, this should not be an important consideration.

2018-11-23 12:54 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +dimension ~2M, for 4d depth is 16, bins per dimension ~65K, and twice more for 128bit Morton number.
"twice more" is confusing, it sounds like it refers to the bin count. I suggest just making a small table of the bin count per dimension, columns 64 bit and 128 bit, rows 3D 4D and 5D. This will make it obvious at a glance.

2018-11-23 12:58 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +##### 4. Switch between the Morton number and floating point coordinates.
I think you should clarify here (you explained this to me earlier):
- By default floating point coordinates are stored.
- The switch to Morton numbers is done only within `ConvertToMD` and `MergeMD`.

If this is the way you intend to do it then my earlier comment below ("I am not yet convinced that this would be less effort than option 3., and it feels more risky in terms of bugs that may occur in the future.") does not apply. I had originally thought the switch would be controlled much more dynamically, influencing many algorithms. If it is only done internally in some algorithms then I do not have major concerns I think, and it seems like a good option.

2018-11-26 06:32 UTC, SimonHeybrock commented on docs/MDSpaceDesign.md
> +and build the workspace, this are only a few functions. All other functionality would not be involved.
@igudich @OwenArnold Over the weekend it occurred to me that this union approach can be made even less intrusive:

1. Assume what I suggested last week (using 96 bit for 3D) works. Then the integers take the same space as the floats do now.
2. Make processing via Morton numbers *an option of the algorithms* (`ConvertToMD` and `MergeMD`).

That is, we do *not* remove the old float coordinate code, we just *add an extra option*. That way anyone who is concerned about precision loss or something else can simply use the old (slow) method, everyone else can use the fast Morton-number method. By using exactly the same memory as the floats (32 bit per dimension) we will also eliminate any potential concerns about memory usage (it is unchanged).

2019-03-05 15:53 UTC, closed without merging